### ISSUE TITLE
Folha de Adesivos com 4 adesivos:  Entre o ideal e o que pode ser feito

### ISSUE THREAD

**Issue by Lucas-cardim** [inhodpr/receita-facil#14]
Eu não sei o que seria mais fácil para fazer, mas vou sugerir aqui como eu acharia mais impactante como intervenção:

Idealmente os adesivos serão colados em copinhos e potes para orientar o uso em períodos do dia (manhã, tarde e noite, por exemplo, sendo possível também em  30 minutos antes do café, antes de dormir ou qualquer outra na vasta possibilidade de necessidades) sendo para tal necessário o uso de ícones associados ao período do dia, como temos nas opções do receituário. Para tal, a possibilidade de utilizarmos mais de um ícone, embora não seja uma necessidade constante, seria melhor pois compreenderia a realidade de mais pacientes que precisam dessa orientação pois não sabem ler.

Abaixo desses ícones de período, colocaríamos o nome do medicamento, a quantidade de miligramas e ícones representativos que auxiliem na compreensão de QUAL medicamento tomar e COMO tomar. Isso também seria melhor sendo possível colocarmos mais de um ícone pois conseguiríamos além da divisão por período que ficaria em cima desses textos/ícones, colocar tambem comprimidos no formato mais próximo do utilizados e outros ícones que guiariam o paciente a tomar o comprimido antes ou depois de uma refeição, um, meio ou dois  comprimidos. 

Acho que não transmitir diretamente da receita para etiquetas (como foi feito no projeto das caixas) e sim criar unidades individuais de construção de etiquetas (permitindo ícones e textos presentes na construção dos receituários, por exemplo) nos daria mais liberdade. Acho que daria MUITO mais trabalho mas ganharíamos qualidade e refino em uma ferramenta que será, assim como já são as receitas, modificadores de prognosticos.

é isso, meu amigo. desculpa o textão. Preciso correr, to atrasado para embarcar pra o Quicé. Beijão e obrigado pro tudo, sempre.

**Comment by Lucas-cardim** [comment]
como estamos nesse projeto, queridão?

**Comment by inhodpr** [comment]
Duplicado da issue #6, fechando.
