### ISSUE TITLE
Adicionar receituário para Jaguarari

### ISSUE THREAD

**Issue by inhodpr** [inhodpr/receita-facil#18]
![jaguarari logo](https://user-images.githubusercontent.com/19919057/232287720-20885c51-2c2d-4a97-b32f-f16d9557769c.png)
![prefeitura de jaguarari](https://user-images.githubusercontent.com/19919057/232287721-abf3cc72-d058-429d-8d94-35c1d46232cd.png)
[jaguarari receita especial.pdf](https://github.com/inhodpr/receita-facil/files/11241712/jaguarari.receita.especial.pdf)
[jaguarari receita simples.pdf](https://github.com/inhodpr/receita-facil/files/11241713/jaguarari.receita.simples.pdf)

**Comment by Lucas-cardim** [comment]
![SEMUS JAGUARARI](https://github.com/inhodpr/receita-facil/assets/128458581/c8795215-17e1-43a0-99ea-8f460faebb32)
[CamScanner 02-09-2023 13.34.pdf](https://github.com/inhodpr/receita-facil/files/11866712/CamScanner.02-09-2023.13.34.pdf)
[CamScanner 02-09-2023 13.32.pdf](https://github.com/inhodpr/receita-facil/files/11866713/CamScanner.02-09-2023.13.32.pdf)

**Comment by inhodpr** [comment]
Esse deu trabalho, mas ta saindo.

Aqui um exemplo de como ta a receita no branch `jaguarari`:
[Receita Fácil Jaguarari.pdf](https://github.com/inhodpr/receita-facil/files/12140163/Receita.Facil.Jaguarari.pdf)

Tem uma versão de teste aqui:
https://20230723t230047-dot-hellodpiresworld.appspot.com/jaguarari

@Lucas-cardim passa pro pessoal de Jaguarari testar, por favor. Se tiver tudo certo, eu faço a pull request e @camposzen revisa.
