### ISSUE TITLE
nova aba chamada "ícones receita"

### ISSUE THREAD

**Issue by Lucas-cardim** [inhodpr/receita-facil#22]
Inho, seria possível criar uma aba chamada "ícones receita" para colocarmos alguns dos grupos de ícones mais utilizados? acho que seria importante esses ícones ficarem ou à direita ou logo abaixo da receita (seria necessário vermos para ver como ficaria cada opção) ,contudo, não sei se será possível (acho que abaixo, para as construções maiores, é o que acaba nos restando mas temos muitas construções não tão grande que ficariam bem à direita da receita digitada, como atualmente ficam os ícones escolhidos individualmente. 

OBSERVAÇÃO IMPORTANTE: !!!!!!!!!!!!
Além de não aparecer números antes das imagens que escolhermos nessa aba para a receita, seria importante que os títulos também não aparecessem na receita, apenas na coluna para que as imagens fossem escolhidas. Seria possível?

![3xdia antes das refeições cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/fc2dcb46-129e-40a9-849a-fd29f6c311a1)
![3xdia antes das refeições cp](https://github.com/inhodpr/receita-facil/assets/128458581/f2208d41-620a-4bc1-97a9-2313e40985fe)
![3xdia após as refeições capsula](https://github.com/inhodpr/receita-facil/assets/128458581/3b1ceea3-cef2-464f-a59c-07c4a6acb788)
![3xdia após refeições cp](https://github.com/inhodpr/receita-facil/assets/128458581/81ae2c9f-3ea0-4c83-9b1e-2dce790a09ae)
![3Xdia cp](https://github.com/inhodpr/receita-facil/assets/128458581/1b19bf91-ad09-44a2-bbb4-cee2896162fb)
![capsula na cama](https://github.com/inhodpr/receita-facil/assets/128458581/3e11cee5-24c0-41d1-a05e-4176a6bdfd2b)
![comprimido na cama](https://github.com/inhodpr/receita-facil/assets/128458581/78e212ff-dc76-43f3-8b39-ee1269dfa7e9)
![jejum manhã capsula](https://github.com/inhodpr/receita-facil/assets/128458581/f2c09ffd-3f1a-4121-b866-a63214b636bf)
![jejum manhã cp](https://github.com/inhodpr/receita-facil/assets/128458581/b45e17b1-1c56-4e29-840e-3b0c33afbf07)
![manhã e noite após refeição cp](https://github.com/inhodpr/receita-facil/assets/128458581/3a518ec2-9b76-49ff-9f80-48ac1506ac11)
![manhã e noite cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/77952341-bca1-4c04-b755-7350228ab7bf)
![manhã e noite cp](https://github.com/inhodpr/receita-facil/assets/128458581/3849795c-a2ef-496e-bcc9-2fa44bcbfb75)
![metformina 3Xdia](https://github.com/inhodpr/receita-facil/assets/128458581/6a8be96d-d87f-4fc7-8673-4d46ea19df4f)

**Comment by Lucas-cardim** [comment]
![atb líquido 4xdia](https://github.com/inhodpr/receita-facil/assets/128458581/2998cff5-ad59-4290-a584-17fb732ad724)

**Comment by Lucas-cardim** [comment]
![atb 4xdia cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/c0d9955d-3505-4de2-b85f-20b2e41da8e1)
![atb 4xdia cp](https://github.com/inhodpr/receita-facil/assets/128458581/29e1642c-f97d-444e-b5b9-75f14a8cbe3a)

**Comment by Lucas-cardim** [comment]
![tópico manhã e noite](https://github.com/inhodpr/receita-facil/assets/128458581/6f4b4792-2615-43e4-8561-71a2a70e46f3)

**Comment by Lucas-cardim** [comment]
![3xdia horário fixo cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/cf9338e8-1b73-4f9a-8155-ddf4bed3be00)
![3xdia horário definível cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/5cdc3525-9de6-4c65-be36-80997954f04c)
![3xdia horário definível cp](https://github.com/inhodpr/receita-facil/assets/128458581/88bb185d-d209-4ba5-972e-48a53b909b82)
![liquido 3x dia horário definível](https://github.com/inhodpr/receita-facil/assets/128458581/bee45db9-c5d3-4d42-9713-2cee94765058)
![liquido manha horário definível](https://github.com/inhodpr/receita-facil/assets/128458581/8afabfef-f4b0-44bf-b884-4980d5ce29d3)
![liquido manhã e noite horário definível](https://github.com/inhodpr/receita-facil/assets/128458581/81b1f34c-ad52-4ab3-a59e-00b8ab8d4135)
![liquido manhã e noite](https://github.com/inhodpr/receita-facil/assets/128458581/6b0c243f-6357-4044-83c9-5da8a2c0d1ab)
![liquido manhã](https://github.com/inhodpr/receita-facil/assets/128458581/52fe8ca6-a1ce-4c8e-98cc-9cf0b26609e2)
![liquido noite](https://github.com/inhodpr/receita-facil/assets/128458581/c2869010-e03e-4a22-8493-78b0dce40eca)
![liquido tarde horário definível](https://github.com/inhodpr/receita-facil/assets/128458581/c4f9f4e8-0246-447a-8a04-9711f8ecc17f)
![liquido tarde](https://github.com/inhodpr/receita-facil/assets/128458581/57f3353b-2a03-4f18-afa2-d3f71821c355)
![3xdia horário fixo cp](https://github.com/inhodpr/receita-facil/assets/128458581/e6aca845-d19e-4609-842c-6a858f1e8874)

**Comment by Lucas-cardim** [comment]
RELEMBRANDO A OBSERVAÇÃO IMPORTANTE:
AO ESCOLHER O GRUPO DE ÍCONES NA BARRA DA DIREITA (nomeada até o momento como "ícones receita") é importante que a imagem apareça SEM NÚMEROS OU TÍTULOS. NO MOMENTO A ABA IMAGENS, POR EXEMPLO, ESTÁ LANÇANDO A IMAGEM COM O TÍTULO MANTIDO **(E É BOM QUE FIQUE ASSIM. O QUE EU QUERO É QUE NA ABA "ícones receita" ao clicar na escolha apareça apenas a imagem, sem número e sem título)**

**Comment by Lucas-cardim** [comment]
![image](https://github.com/inhodpr/receita-facil/assets/128458581/7ce5ddfa-a1fe-43bf-9b04-e381946785c4)
na parte de imagens os títulos ainda são mantidos. e é bom que fiquem mantidos. na parte dos packs de ícones não é para aparecer nem números e nem os títulos.

**Comment by Lucas-cardim** [comment]
![manhã e noite pré-refeições](https://github.com/inhodpr/receita-facil/assets/128458581/5139df0e-a491-4d76-92e4-d34e37c9c2b2)

**Comment by inhodpr** [comment]
Submeti a mudança e deve entrar em produção logo mais.
Criei uma categoria chama "Packs de ícones", por enquanto está lá no fim da lista. Vamos repensar essa ordenação logo.
As imagens dessa categoria sao exibidas sem contadores e sem títulos.
Adicionei todas as imagens do bug nessa pasta.

Testa aí e vê se ta tudo certo.

**Comment by Lucas-cardim** [comment]
é possível  introduzir uma linha fina abaixo de cada um dos ícones, para evidenciar a separação e evitar a confusão entre o medicamento o qual os ícones corresponde e o medicamento que se apresentará abaixo?

**Comment by Lucas-cardim** [comment]
duas intervenções que julgo MUITO NECESSÁRIAS:
1. introduzir uma linha fina abaixo de cada uma das imagens de pack 
2.colocar um pré-espaçamento equivalente a uma linha quando introduzirmos um novo medicamento na receita, para aumentar a distância entre o ícone associado medicamento acima e o próximo medicamento escrito 
![image](https://github.com/inhodpr/receita-facil/assets/128458581/4aff9db1-c808-42ba-a0b0-01b840489b5d)

**Comment by Lucas-cardim** [comment]
Meu amado amigo. você conseguindo colocar essa aba logo abaixo da aba DIGITAR QUALQUER MEDICAMENTO ficaria lindo!! Fazendo isso e as linhas acho que zeramos esse jogo

**Comment by Lucas-cardim** [comment]
![1cp 4xdia](https://github.com/inhodpr/receita-facil/assets/128458581/05788e56-4fc3-41f2-b399-b0bf84a028b7)
![2cps 4xdia](https://github.com/inhodpr/receita-facil/assets/128458581/7b2df76a-0c3f-4596-a15b-1b91567b580b)

**Comment by Lucas-cardim** [comment]
acho que essas duas acima fecham o pack basico. VOCE É FODASTICO
MUITO OBRIGADO!

**Comment by Lucas-cardim** [comment]
Amado inhoso. Passei a manhã pensando nos principais possíveis packs de ícones para comprimidos, cápsulas e cremes. A ideia seria dividir os packs em 3 abas distintas

**Comment by Lucas-cardim** [comment]
ABA "ícones comprimidos"
![2xDia comprimido antes refeição](https://github.com/inhodpr/receita-facil/assets/128458581/8f51da35-3a19-49af-abcf-6f4b739866bf)
![2xDia comprimido pós refeição](https://github.com/inhodpr/receita-facil/assets/128458581/6b45bad1-741d-4d34-8476-3cc89f4979f1)
![2xDia comprimido](https://github.com/inhodpr/receita-facil/assets/128458581/dc80e0ca-3baf-4dbf-8d6e-290914232643)
![3xDia comprimido antes refeição](https://github.com/inhodpr/receita-facil/assets/128458581/c84abe3f-0ad5-4f5d-b387-dbb1ecdca7b0)
![3xDia comprimido horário fixo (atb e outros)](https://github.com/inhodpr/receita-facil/assets/128458581/2ad9e187-e342-4e11-b4d9-954113bf8b02)
![3xDia comprimido pós refeição](https://github.com/inhodpr/receita-facil/assets/128458581/9f6d9fd5-5bf1-4202-98fd-1975168d2353)
![3xDia comprimido](https://github.com/inhodpr/receita-facil/assets/128458581/24ce671a-582d-4811-a27b-dd96002ab52d)
![3xDia metformina](https://github.com/inhodpr/receita-facil/assets/128458581/d3c03812-f076-47d6-afc2-ce1561126122)
![4Xdia 02comprimidos](https://github.com/inhodpr/receita-facil/assets/128458581/bdf2cfdc-2404-4734-89d5-41bb31645018)
![4xDia comprimido horário fixo (atb e outros)](https://github.com/inhodpr/receita-facil/assets/128458581/ce8f7232-4453-4c47-97b7-c9ff79eba08f)
![4xDia comprimido](https://github.com/inhodpr/receita-facil/assets/128458581/8df753f1-09de-4c2f-b15b-d7b2dc003a61)
![30 minutos antes do almoço comprimido](https://github.com/inhodpr/receita-facil/assets/128458581/cecda043-e553-4897-9d22-50d5334da25a)
![30 minutos antes do almoço](https://github.com/inhodpr/receita-facil/assets/128458581/c445750c-2e66-4d53-9ddf-37b590b13d73)
![30 minutos antes do café comprimido](https://github.com/inhodpr/receita-facil/assets/128458581/98429492-e4b2-47bd-802f-9e4ab3e9a003)
![30 minutos antes do jantar](https://github.com/inhodpr/receita-facil/assets/128458581/23e7a0a4-3094-4df6-a456-0de12519ac60)
![manhã comprimido](https://github.com/inhodpr/receita-facil/assets/128458581/a54c254c-edc6-4ee2-a36d-6e1f4b8b0448)
![na cama comprimido](https://github.com/inhodpr/receita-facil/assets/128458581/6280f006-0248-4418-bc27-de00b12752a8)
![noite comprimido](https://github.com/inhodpr/receita-facil/assets/128458581/21b4e171-fd1b-4ead-bb88-569b0e0babba)
![pós almoço comprimido](https://github.com/inhodpr/receita-facil/assets/128458581/8a7257ff-ec67-4c48-bd1a-d5add05f703f)
![pós café comprimido](https://github.com/inhodpr/receita-facil/assets/128458581/8d5ce93e-5d78-48f1-8983-6181825c320e)
![pós jantar comprimido](https://github.com/inhodpr/receita-facil/assets/128458581/31a64729-f0c6-4875-be3f-2a51a0cc5f7e)
![pré almoço comprimido](https://github.com/inhodpr/receita-facil/assets/128458581/5f51c9ae-44cd-4e28-89a9-52e4a87ea050)
![pré café comprimido](https://github.com/inhodpr/receita-facil/assets/128458581/ed209cc7-8d70-4d36-a99c-3ade8a9181b3)
![pré jantar comprimido](https://github.com/inhodpr/receita-facil/assets/128458581/741f24ea-7bb3-4da7-b688-d112c735c313)
![tarde comprimido](https://github.com/inhodpr/receita-facil/assets/128458581/bcc2ec49-7ad9-492d-9de5-e21d216669e8)

**Comment by Lucas-cardim** [comment]
ABA "ícones cápsulas"
![30 minutos antes do jantar cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/dede228b-a18f-4b42-97c0-a346297889d1)
![na cama cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/b850f9fa-14b9-4d6d-a20b-5759d4ed012e)
![pós almoço cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/6e875021-ed18-4b09-8dd2-b157dff1bf0b)
![pós café cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/5d070044-0890-4ead-87a8-4159d48ea587)
![pós jantar cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/a1aed95b-91f6-4541-9c60-761beb0edd56)
![pré almoço cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/43c71fa1-fc11-4f98-86de-619d42ee7907)
![pré café cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/a8bd96a8-5458-49d8-8ef5-b6ba79544d6a)
![pré jantar cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/f7f6f1d6-b6d7-4bb2-8eed-e23954f4ff02)
![2xDia cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/0264389c-068a-472e-af2b-c4208552d841)
![3xDia cápsula antes refeição](https://github.com/inhodpr/receita-facil/assets/128458581/2429f965-3147-434b-b6bc-5599fc574233)
![3xDia cápsula horário fixo (atb e outros)](https://github.com/inhodpr/receita-facil/assets/128458581/4cbca0c1-e6dd-41d7-90d6-e38c9ae9a57e)
![3xDia cápsula pós refeição](https://github.com/inhodpr/receita-facil/assets/128458581/741da474-6743-43aa-a63f-055085bc0c18)
![3xDia cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/7da1e2b5-730c-45a5-8aca-760dea9f1ecf)
![4xDia cápsula horário fixo (atb e outros)](https://github.com/inhodpr/receita-facil/assets/128458581/29ffb2b6-3244-42eb-8cf1-2fc9062f05c4)
![30 minutos antes do almoço cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/4cd3fbc5-33bf-4324-891a-70c851b3487f)
![30 minutos antes do café cápsula](https://github.com/inhodpr/receita-facil/assets/128458581/64ab36bb-54fc-420d-9cdb-cf6173d5106e)

**Comment by Lucas-cardim** [comment]
ABA "ícones líquido"
![4xDia líquido horário fixo (atb e  outros)](https://github.com/inhodpr/receita-facil/assets/128458581/7cc7d198-7c33-4c53-bfa7-553fc25231ca)
![4xDia líquido](https://github.com/inhodpr/receita-facil/assets/128458581/c06c56f4-8206-49c1-9988-f4b88dffa60d)
![horário fixo manhã (corticóide e outros)](https://github.com/inhodpr/receita-facil/assets/128458581/ba6987a3-5274-4eec-92bd-eb4ea00c4ec3)
![liquido tarde horário definível](https://github.com/inhodpr/receita-facil/assets/128458581/324650ba-b959-49c1-85c6-dade19d75536)
![manhã liquido horário definível](https://github.com/inhodpr/receita-facil/assets/128458581/2c12cd58-4d58-4d32-b2aa-81370a2b2ce6)
![manhã líquido](https://github.com/inhodpr/receita-facil/assets/128458581/40a47695-422c-4006-bf3a-3fd1248b51d8)
![noite líquido](https://github.com/inhodpr/receita-facil/assets/128458581/f990a176-f589-4480-b968-3261a4c1bdad)
![tarde líquido](https://github.com/inhodpr/receita-facil/assets/128458581/ffd1a6f8-b2a0-4bfd-8975-169d2e707f49)
![2xDia líquido horário definível](https://github.com/inhodpr/receita-facil/assets/128458581/b84ed7f4-099b-4b88-8583-e9a87621dff0)
![2xdia liquido](https://github.com/inhodpr/receita-facil/assets/128458581/9e6b9858-862b-43a4-9e68-895556c26259)
![2xDia líquido](https://github.com/inhodpr/receita-facil/assets/128458581/4b33d6d2-b3b5-4ac5-b23d-063ebbfc5223)
![3xDia líquido horário definível](https://github.com/inhodpr/receita-facil/assets/128458581/06dcaec2-02dd-4377-b1ce-b612bd076640)
![3xDia líquido](https://github.com/inhodpr/receita-facil/assets/128458581/23fcfbf7-b7de-4142-afb5-44438c47e992)

**Comment by Lucas-cardim** [comment]
ABA "ícones tópico"
![manhã tópico](https://github.com/inhodpr/receita-facil/assets/128458581/52792a16-c1d3-4a99-af5d-84243a820c94)
![noite tópico](https://github.com/inhodpr/receita-facil/assets/128458581/c59830d6-7e25-40b7-b18f-c212ac48f618)
![2xDia tópico](https://github.com/inhodpr/receita-facil/assets/128458581/14cede54-eff1-4d50-972b-c1a422ecbace)

**Comment by inhodpr** [comment]
Podemos quebrar em subcategorias, do jeito que tá lá já?

- Packs de ícones (comprimidos)
- Packs de ícones (cápsulas)
- Packs de ícones (líquido)
- Packs de ícones (tópico)

Aí nao temos nenhuma mudança de código, só direto no datastore.

**Comment by Lucas-cardim** [comment]
acho ótimo !!!
obrigado!!
