### ISSUE TITLE
Layout da plataforma. É possível?

### ISSUE THREAD

**Issue by Lucas-cardim** [inhodpr/receita-facil#33]
se você achar que dá pra fazer, faço um documento associando todos documentos referentes a cada um dos ícones de referência de prescrição. O bom é que muitos podem aparecer em mais de um ícone então é mais uma chance pro cara achar o medicamento correto.
Também deixo no documento as condutas referentes ao ícones condutas. Achas possível? me diz que sim PELO AMOR DE DEUS
![RASCUNHO PLATAFORMA JPG](https://github.com/inhodpr/receita-facil/assets/128458581/87832e04-1936-455c-9014-39e348a9968e)
![RASCUNHO PLATAFORMA PNG](https://github.com/inhodpr/receita-facil/assets/128458581/887876e5-e14f-4b2f-82d9-e08a4f786ee4)

**Comment by Lucas-cardim** [comment]
ATUALIZEI O ESBOÇO
ENTÃO É POSSÍVEL?
![RASCUNHO PLATAFORMA PNG AJUSTE 2](https://github.com/inhodpr/receita-facil/assets/128458581/e347bc1c-00be-492b-96f6-3890c9e6d904)

**Comment by inhodpr** [comment]
Vou fechar esse aqui e centralizar discussão de layout na issue #34.
