### ISSUE TITLE
FEATURE REQUEST: Imagens para o paciente acompanhando a medicação.

### ISSUE THREAD

**Issue by inhodpr** [inhodpr/receita-facil#50]
Para alguns medicamentos, gostaríamos que a receita tivesse, além do texto explicativo, uma imagem que ajudasse a entender como usar e porque usar o remédio. Os ícones de suporte são genéricos, e não cobrem bem todos os casos.

Ideia: adicionar um campo imagem que aponta para uma imagem hospedada em um dos buckets públicos do GCS do projeto, e exibir ela abaixo da descrição.

**Comment by inhodpr** [comment]
Questão: a gente coloca um 'X' pro médico clicar e apagar a imagem, se ele achar q ta poluído demais? Feito o que tem no instructions for doctors?

**Comment by Lucas-cardim** [comment]
Não gostaria que se colocasse um X. as imagens serão basais para o paciente não letrado compreender o uso.  Mas o que voce acha?

**Comment by inhodpr** [comment]
Implementando isso nesse branch aqui:
https://github.com/inhodpr/receita-facil/compare/new-fields?expand=1

Versão de teste do sistema subindo aqui:
https://20240129t223424-dot-hellodpiresworld.appspot.com

Exemplo de receita com isso:
[Receita Fácil - Teste com images e QR Code.pdf](https://github.com/inhodpr/receita-facil/files/14090423/Receita.Facil.-.Teste.com.images.e.QR.Code.pdf)
