### ISSUE TITLE
FEATURE REQUEST: link para vídeos de apoio ao uso do medicamento, com QR codes.

### ISSUE THREAD

**Issue by inhodpr** [inhodpr/receita-facil#51]
Hoje temos imagens e vídeos separados das drogas. Algumas imagens e vídeos são relevantes para medicamentos específicos, e era ideal que eles sempre aparecessem quando o remédio fosse adicionado à receita, sem que o médico precise lembrar de adicioná-los separadamente.

A parte de imagens está descrita na issue #50. Essa issue é sobre links para vídeos, exibidos na receita via QR Code.

Temos que adicionar dois campos novos na droga: `url` e `url_description`. Quando a droga é adicionada na receita, colocamos embaixo da descrição o conteúdo do campo `url_description` e um QR code que leve para o endereço do campo `url`. 

Usamos a mesma lib do Google para gerar QR code que usamos aqui: https://github.com/inhodpr/receita-facil/blob/b0b997b1d5cb61afae8b7e9356e70f5628c419d1/static/js/receitaDiv.js#L162

**Comment by inhodpr** [comment]
Se tiver imagem e QR code, o QR code aparece abaixo da imagem.

**Comment by Lucas-cardim** [comment]
isso!

**Comment by inhodpr** [comment]
Implementando isso nesse branch aqui:
https://github.com/inhodpr/receita-facil/compare/new-fields?expand=1

Versão de teste do sistema subindo aqui:
https://20240129t223424-dot-hellodpiresworld.appspot.com/

Exemplo de receita com isso:
[Receita Fácil - Teste com images e QR Code.pdf](https://github.com/inhodpr/receita-facil/files/14090423/Receita.Facil.-.Teste.com.images.e.QR.Code.pdf)
