### ISSUE TITLE
Exibir ícones de apoio com 4 ícones por linha

### ISSUE THREAD

**Issue by Lucas-cardim** [inhodpr/receita-facil#55]
Caro CEO, Mestre Davi Pires Rios,

escrevo do alto da minha insignificância para solicitar um ajuste importante nos atuais ícones disponíveis para preenchimento de receitas na plataforma cuidadoparatodos.com .  

Os ícones que lançarei abaixo, estão nomeados em uma ordem numeral crescente, seguindo uma lógica de uso que será em muito otimizada caso a disposição dos mesmos se dê em linhas contendo 4 colunas cada uma. Repito: 4 colunas por linha, seguindo a ordem numerária colocada, criará uma disposição dos ícones que muito facilitará a vida do usuário do programa. Esses ícones podem ser os primeiros a serem ofertados no campo de visão após se clicar na seta de abertura, um novo bucket poderia até mesmo ser criado com o nome: ícones básicos. 

Contudo, nobre Mestre, Rei da programação, Maior e Melhor filho do meio do grande ATAGIBA ( vulgo GEIBOL, um dos seres humanos mais inteligentes, trabalhadores e engraçados que já tive a honra de conhecer, Marido da magnífica Conceição), a disponibilidade dos tamanhos desses ícones na plataforma, após enviados em formato .PNG para os famigerados BUCKETS segue sendo uma caixa de pandora para mim.  Por vezes aparecem no programa de forma grande, por vezes de forma microscópica, como estão aparecendo os atuais que te envio. Tomei por cuidado manter as imagens em um padrão de tamanho no formato .PNG nos ícones de número 01 até o de número 28 e posteriormente em outro padrão de tamanho (por questões pictográficas) nos ícones de número 29 até 40.  IMPLORO, Ó NOBRE AMIGO, QUE COM SUA SAPIÊNCIA SEJA POSSÍVEL AVALIAR COM CUIDADO UM TAMANHO DECENTE PARA QUE ESSAS IMAGENS QUE TANTO TRABALHO DERAM PARA SER FEITAS E AJUSTADAS POSSAM SER DECENTEMENTE PROJETADAS EM TAMANHO ROBUSTO NA RECEITA A SER FEITA, MELHORANDO ASSIM A VIDA DE MILHARES DE PACIENTES NÃO LETRADOS.

Pergunto desde já à vossa senhoria se algo faltou em minha exposição (talvez concisão, reconheço), peço desculpas por texto tão extenso, sonho com uma conversa por vídeo quando sua nobre agenda assim permitir.

**Comment by Lucas-cardim** [comment]
![01 MANHÃ  UM comprimido ANTES do cafe da manha](https://github.com/inhodpr/receita-facil/assets/128458581/043bf968-065e-468f-b532-ba9dd2899797)
![02 MANHÃ UM comprimido DEPOIS do cafe da manha](https://github.com/inhodpr/receita-facil/assets/128458581/f060e489-65c0-434e-bdd5-bceb5f03cea0)
![03 MANHÃ DOIS comprimidos ANTES do cafe da manha](https://github.com/inhodpr/receita-facil/assets/128458581/fd5af3d6-d05f-4c51-9bc2-b55c70fbd520)
![04 DOIS comprimidos DEPOIS do cafe da manha](https://github.com/inhodpr/receita-facil/assets/128458581/a3dcfacf-038f-4ec1-9326-b031779dad94)
![05 MANHÃ UMA cápsula ANTES do cafe da manha](https://github.com/inhodpr/receita-facil/assets/128458581/ddc880e3-fbae-4150-b260-d5a0b5bbf820)
![06 MANHÃ UMA cápsula DEPOIS do cafe da manha](https://github.com/inhodpr/receita-facil/assets/128458581/20efa3bb-aba8-4205-973c-75302b4293b8)
![07 MANHÃ DUAS cápsulas ANTES do cafe da manha](https://github.com/inhodpr/receita-facil/assets/128458581/296b71b1-8463-47e8-86ea-99aac4dafc8f)
![08 MANHÃ DUAS cápsulas depois do cafe da manha](https://github.com/inhodpr/receita-facil/assets/128458581/bb397288-dea9-4b40-bff5-706e191d10e4)
![09 TARDE UM comprimido ANTES do almoço](https://github.com/inhodpr/receita-facil/assets/128458581/ad950102-76bb-48cd-b84b-8d36ab6cbc5e)
![10 TARDE UM comprimido DEPOIS do almoço](https://github.com/inhodpr/receita-facil/assets/128458581/03fc48a8-df4d-4401-99e7-c7256c0e7431)
![11 TARDE DOIS comprimidos ANTES do almoço](https://github.com/inhodpr/receita-facil/assets/128458581/99e4e7b2-2012-4149-ba7a-184c3bc716e5)
![12 TARDE DOIS comprimidos DEPOIS do almoço](https://github.com/inhodpr/receita-facil/assets/128458581/fb794a83-b601-4589-b0bd-134207a976e1)
![13 TARDE UMA cápsula ANTES  do almoço](https://github.com/inhodpr/receita-facil/assets/128458581/33483589-f523-4b7e-a438-7e2d7d458b71)
![14 TARDE UMA cápsula DEPOIS do almoço](https://github.com/inhodpr/receita-facil/assets/128458581/e2dff3cf-4561-4a93-b7a4-6586bb7f0f58)
![15 TARDE DUAS cápsulas ANTES do almoço](https://github.com/inhodpr/receita-facil/assets/128458581/db7dad1f-cd26-4f4e-8f27-9581b1bfa961)
![16 TARDE DUAS cápsulas DEPOIS  do almoço](https://github.com/inhodpr/receita-facil/assets/128458581/97a2696a-1044-4dc6-b556-68d2b30b8920)
![17 NOITE UM comprimido antes do jantar](https://github.com/inhodpr/receita-facil/assets/128458581/9dfc80e9-edd3-42f5-9e6d-1a5183849e4b)
![18 NOITE UM comprimido DEPOIS do jantar](https://github.com/inhodpr/receita-facil/assets/128458581/292c3790-d066-456c-842d-72b8f04fdc09)
![19 NOITE  DOIS comprimidos ANTES do jantar](https://github.com/inhodpr/receita-facil/assets/128458581/cbf6e553-9096-437b-aeef-68fff6a4bcfd)
![20 NOITE  DOIS comprimidos DEPOIS do jantar](https://github.com/inhodpr/receita-facil/assets/128458581/54f069cf-87a6-4b5b-96d6-7ee60845693b)
![21 NOITE UMA cápsula ANTES do jantar](https://github.com/inhodpr/receita-facil/assets/128458581/a18bed2d-bf3a-4131-97aa-53b4332f93bc)
![22 NOITE UMA cápsula DEPOIS do jantar](https://github.com/inhodpr/receita-facil/assets/128458581/6fe20d6b-b1e1-4ee3-8f53-552059e6b6e8)
![23 NOITE DUAS cápsulas antes do jantar](https://github.com/inhodpr/receita-facil/assets/128458581/986f1b25-aef4-4dda-ae00-eb1335e82eaf)
![24 NOITE DUAS cápsulas DEPOIS do jantar](https://github.com/inhodpr/receita-facil/assets/128458581/59f6ceaa-1c18-45af-8349-c6ad985ab261)
![25 NOITE UM comprimido ANTES de DORMIR MULHER](https://github.com/inhodpr/receita-facil/assets/128458581/5c1ac041-5ed0-48f2-8b93-66694b5ddad3)
![26 NOITE UMA cápsula ANTES de DORMIR MULHER](https://github.com/inhodpr/receita-facil/assets/128458581/4e3379e4-0fc7-48b7-82cf-791db9a45fc1)
![27 NOITE UM comprimido ANTES de Dormir HOMEM](https://github.com/inhodpr/receita-facil/assets/128458581/3da05dce-200a-4405-b08a-a3a5f70f74c6)
![28 NOITE UMA CÁPSULA ANTES de DORMIR HOMEM](https://github.com/inhodpr/receita-facil/assets/128458581/4be420fb-6df5-4b6c-8465-9104b8e17848)
![29 CAPSULA 30MIN ANTES DO CAFÉ DA MANHÃ](https://github.com/inhodpr/receita-facil/assets/128458581/45564605-2d35-4bc4-82d3-1c5f9add264f)
![30 COMPRIMIDO 30MIN ANTES DO CAFÉ DA MANHÃ](https://github.com/inhodpr/receita-facil/assets/128458581/c68bdd5a-aeff-4c25-8b79-871ae9b9bf75)
![31 CÁPSULA 30MIN DEPOIS DO CAFÉ DA MANHÃ](https://github.com/inhodpr/receita-facil/assets/128458581/4884b993-ab51-4589-9762-c3414ac66fc4)
![32 COMPRIMIDO 30MIN DEPOIS DO CAFÉ DA MANHÃ](https://github.com/inhodpr/receita-facil/assets/128458581/763f2bcc-83dc-45b5-b3da-e97f5bb0ec13)
![33 CÁPSULA 30MIN ANTES DO ALMOÇO](https://github.com/inhodpr/receita-facil/assets/128458581/6a4e1bbe-8b2f-4a7f-9fba-c406540eb1a9)
![34 COMPRIMIDO 30MIN ANTES DO ALMOÇO](https://github.com/inhodpr/receita-facil/assets/128458581/7162b3bc-3c5a-42db-9ef7-627f5c0a780d)
![35 CÁPSULA 30MIN DEPOIS DO ALMOÇO](https://github.com/inhodpr/receita-facil/assets/128458581/9bc20fb2-f435-458b-be2f-06205a58f7f6)
![36 COMPRIMIDO 30MIN DEPOIS ALMOÇO](https://github.com/inhodpr/receita-facil/assets/128458581/cfc70d8f-12dd-449c-823d-b9a1e4d84632)
![37 CAPSULA 30MIN ANTES DO JANTAR](https://github.com/inhodpr/receita-facil/assets/128458581/340c175e-89e2-43fe-a5d5-1f1cfcbab452)
![38 COMPRIMIDO 30MIN ANTES DO JANTAR](https://github.com/inhodpr/receita-facil/assets/128458581/87140f31-d0c8-4781-a2fe-b3a193989a06)
![39 CAPSULA 30MIN APOS O JANTAR](https://github.com/inhodpr/receita-facil/assets/128458581/27d44482-d37d-4831-8a6c-3f0b3ddc35f8)
![40 COMPRIMIDO 30MIN DEPOIS DO JANTAR](https://github.com/inhodpr/receita-facil/assets/128458581/17a8ed06-39e9-48f1-bdb8-460d9d0b4e52)

**Comment by inhodpr** [comment]
Comecei a mexer aqui, subi os ícones para um bucket novo '00 Combinados'.
https://console.cloud.google.com/storage/browser/receita-facil-support-icons/00%20Combinados?project=hellodpiresworld&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

Isso bagunçou a lista de ícones que a gente mostra em prod, então fiz esse push aqui pra poder brincar com isso sem bagunçar o que tá em produção.
https://github.com/inhodpr/receita-facil/pull/64

**Comment by inhodpr** [comment]
Fechando.
