### ISSUE TITLE
Formatação dos textos da receita: Fonte e espaçamento

### ISSUE THREAD

**Issue by Lucas-cardim** [inhodpr/receita-facil#8]
sugestão:
Fonte: Arial sem serifa  ( acho que o tamanho atual está bom).
Nome do medicamento, tracinhos e quantidade do medicamento em NEGRITO, no formato lindão MONOESPAÇADO que você propôs.
O texto correspondente às instruções de uso não ficariam em negrito, podem manter o atual tamanho das fontes, e se possível ficariam (caso já não sejam) alinhados à esquerda.

**Comment by inhodpr** [comment]
This is now fixed.
