### ISSUE TITLE
Digitar informações extras do medicamento para o médico ler

### ISSUE THREAD

**Issue by inhodpr** [inhodpr/receita-facil#9]
Quanto a possibilidade de digitar informações que guiem o profissional de saúde na prescrição utilizando espaçamento de linhas entre essas informações e prescrição da receita em si, achas possível? Atualmente a complementação da metformina, por exemplo, se encontra colada ao texto da receita. Seria possível poder digitar informações sobre as medicações colocando espaços entre a receita em si e esses textos complementares?

**Comment by Lucas-cardim** [comment]
penso que se cada medicação tivesse abaixo uma outra barrinha com informações a serem lidas apenas pelo profissional de saúde ganharíamos muito! Explico:
- Muitos medicamentos de uso contínuo demandam de exames de acompanhamento periódico e exames de imagem para que a gratuidade do seu fornecimento ocorra por programas federais. A maioria dos médicos não sabe disso.Se conseguíssemos isso, seria uma verdadeira integração entre os programas de fornecimento de medicamentos e pacientes mais humildes. uma revolução.

- Muitos medicamentos dependem de avaliações laboratoriais criteriosas para início de uso, manutenção de uso e quem também indiquem redução progressiva ou suspensão imediata do uso. Muitos profissionais de saúde não sabem disso e geram o caos. 
- Muitos medicamentos não podem ser tomados em um mesmo período que outros ou diante de outras comorbidades já vigentes, muitos medicamentos tem restrição de idade para uso.

**Comment by inhodpr** [comment]
Teste com Metformina 850mg para gestantes.
Adicionei a propriedade `instructions_for_doctors` na base de dados. Fica exibido assim:

<img width="1475" alt="Screenshot 2023-06-03 at 12 38 03" src="https://github.com/inhodpr/receita-facil/assets/19919057/fce58737-7b91-443d-a969-4f51a82d73b7">

Clicando no botão do X, a caixa desaparece.
Ela também não aparece na hora da impressão. Mesmo que você não aperte no X.

Vou submeter e fazer a pull request.

**Comment by inhodpr** [comment]
We forgot that, after closing the red box, when we add a new drug we redraw the whole prescription div, so it shows up again. Reopening because it needs to stay closed.
